# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    name: Build - Java ${{ matrix.java-version }} on ${{ matrix.operating-system }}:${{ matrix.architecture }}
    strategy:
      matrix:
#        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
        operating-system: [ubuntu-latest, macOS-latest]
        java-version: [8, 11, 14]
        architecture: ['x64']
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java ${{ matrix.java-version}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
        architecture: ${{ matrix.architecture }}
    - name: Build with Maven
      run: mvn -B package -Dmaven.compiler.source=${{ matrix.java-version }} -Dmaven.compiler.target=${{ matrix.java-version }} --file pom.xml
